driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/fixtures

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: centos-7.0
  - name: fedora-19
  - name: fedora-20
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: freebsd-9.2
    run_list:
    - recipe[freebsd::portsnap]

# # Uncomment after logging into Atlas
# - name: windows-8.1-professional
#   driver:
#     box: chef/windows-8.1-professional # private

# - name: windows-2008r2-standard
#   driver:
#     box: chef/windows-server-2008r2-standard # private

# - name: macosx-10.10
#   driver:
#     box: chef/macosx-10.10 # private

# - name: macosx-10.9
#   driver:
#     box: chef/macosx-10.9 # private

suites:
- name: default
  run_list:
  - recipe[git]
  attributes: {}

- name: source
  excludes: ["ubuntu-12.04", "ubuntu-10.04"]
  run_list:
  - recipe[git::source]
  attributes: {}

# servespec on windows is pretty raw.  
# os detection forces us to use a separate suite.
# rather than the usual os[:family] tricks

- name: default-windows
  includes: [
    'windows-8.1-professional', 
    'windows-2008r2-standard'
  ]
  run_list:
  - recipe[git]
  attributes: {}
